"""empty message

Revision ID: 1ea599e1a5e5
Revises: 1de6566b0b22
Create Date: 2015-06-19 16:07:48.982742

"""

# revision identifiers, used by Alembic.
revision = '1ea599e1a5e5'
down_revision = '1de6566b0b22'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('galleries', 'image_2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('galleries', 'image_3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('galleries', 'image_4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('galleries', 'image_5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('galleries', 'image_5',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('galleries', 'image_4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('galleries', 'image_3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('galleries', 'image_2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    ### end Alembic commands ###
