"""empty message

Revision ID: 36042f1194f0
Revises: 1ea599e1a5e5
Create Date: 2015-06-19 16:14:49.973569

"""

# revision identifiers, used by Alembic.
revision = '36042f1194f0'
down_revision = '1ea599e1a5e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('company_name', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'cards', 'companies', ['company_name'], ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'company_name')
    ### end Alembic commands ###
