"""empty message

Revision ID: 54fcb88140f3
Revises: 5477560f5ff4
Create Date: 2015-06-15 15:30:59.641577

"""

# revision identifiers, used by Alembic.
revision = '54fcb88140f3'
down_revision = '5477560f5ff4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
